<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.538">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Fathan Depta Vernando 220204120">
<meta name="dcterms.date" content="2024-01-11">

<title>Pengaruh Ekspor Impor Terhadap Pertumbuhan Ekonomi Indonesia Pada Periode 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Impor Terhadap Pertumbuhan Ekonomi Indonesia Pada Periode 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Fathan Depta Vernando 220204120 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 11, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>Politeknik APP Jakarta</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Pertumbuhan ekonomi suatu negara saat ini sangat terkait dengan kondisi perekonomian global. Interaksi ekonomi antar negara menjadi faktor utama dalam memastikan pertumbuhan ekonomi suatu negara. Fenomena ini menimbulkan daya saing sebagai elemen kunci dalam persaingan antarnegara untuk mendapatkan keuntungan dari globalisasi perekonomian yang semakin meluas. Keuntungan dari keterbukaan perekonomian yang meluas dapat tercermin dari kondisi neraca pembayaran suatu negara.</p>
<p>Bank Indonesia (BI) mendefinisikan neraca pembayaran sebagai catatan transaksi ekonomi antara penduduk Indonesia dengan pihak non-residen dalam suatu periode tertentu. Suatu negara dikatakan memiliki surplus neraca pembayaran ketika terjadi kelebihan nilai ekspor dan investasi dibandingkan kewajiban yang dibayarkan kepada negara lain, sebaliknya, kondisi neraca pembayaran defisit terjadi saat impor lebih besar daripada ekspor. Neraca pembayaran yang mengalami surplus atau defisit dapat berdampak pada pertumbuhan ekonomi suatu negara.</p>
<p>Menurut Thirlwall (1979), neraca pembayaran berperan sebagai kendala terhadap pertumbuhan output. Peningkatan produksi domestik akibat kenaikan impor dapat menyebabkan terjadinya defisit, yang dapat mengakibatkan penurunan permintaan atau melemahnya nilai tukar riil. Pertumbuhan ekonomi suatu negara akan lebih cepat jika elastisitas pendapatan ekspor lebih besar daripada impor. Hal ini dikarenakan negara tidak dapat tumbuh lebih cepat daripada tingkat pembayaran yang harus dilakukan, terutama jika rasio utang luar negeri terhadap Pertumbuhan Domestik Bruto (PDB) tinggi, yang dapat mengakibatkan kehilangan kepercayaan dari pihak internasional dan eksternal.</p>
<p>Penelitian ini bertujuan untuk mengkaji bagaimana neraca pembayaran memengaruhi pertumbuhan ekonomi Indonesia selama 10 tahun terakhir. Fokus penelitian ini adalah pada neraca berjalan dalam Neraca Pembayaran Indonesia (NPI), khususnya dalam konteks ekspor dan impor. Melalui analisis regresi multivariat atau Ordinary Least Square (OLS), penelitian ini akan menginvestigasi pengaruh ekspor dan impor terhadap pertumbuhan ekonomi Indonesia selama masa 10 tahun terakhir.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Penelitian ini menginvestigasi dan menganalisis dampak ekspor dan impor terhadap pertumbuhan ekonomi selama 10 tahun terakhir. Lingkup penelitian ini mencakup variabel-variabel yang terkait dengan judul penelitian, yakni ekspor, impor, dan PDB.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<p>Dari tinjauan latar belakang penelitian ini, dapat diajukan beberapa permasalahan utama sebagai berikut:</p>
<ol type="1">
<li>Bagaimana dampak ekspor terhadap pertumbuhan ekonomi Indonesia selama periode 10 tahun terakhir ?</li>
<li>Bagaimana efek impor terhadap pertumbuhan ekonomi Indonesia dalam 10 tahun terakhir ?</li>
</ol>
</section>
<section id="tujuan-penelitian-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-penelitian-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan Penelitian dan Manfaat Penelitian</h3>
<p>Berdasarkan uraian latar belakang dan rumusan masalah penelitian ini, tujuan dan manfaat penelitian dapat dirinci sebagai berikut:</p>
<ol type="1">
<li>Menyelidiki dampak ekspor terhadap pertumbuhan ekonomi Indonesia selama 10 tahun terakhir</li>
<li>Menyelidiki efek impor terhadap pertumbuhan ekonomi Indonesia selama 10 tahun terakhir</li>
</ol>
<p>Manfaat penelitian ini melibatkan pemahaman yang lebih baik tentang pengaruh ekspor dan impor terhadap pertumbuhan ekonomi Indonesia selama 10 tahun terakhir. Hasil penelitian ini dapat memberikan wawasan penting bagi kebijakan ekonomi dan pengambilan keputusan terkait upaya mengatasi dampak ekonomi</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan dalam laporan ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Tugas Metopel/Fathan Depta Vernando'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<section id="pertumbuhan-ekonomi" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="pertumbuhan-ekonomi"><span class="header-section-number">2.1</span> Pertumbuhan Ekonomi</h3>
<p>Menurut Sukirno (2011), pertumbuhan ekonomi dapat didefinisikan sebagai perkembangan aktivitas ekonomi suatu negara yang mengakibatkan peningkatan produksi barang dan jasa dalam masyarakat, serta meningkatnya kesejahteraan masyarakat secara umum. Oleh karena itu, pertumbuhan ekonomi dapat dianggap sebagai indikator kemajuan suatu perekonomian dari satu periode waktu ke periode waktu berikutnya. Peningkatan kemampuan suatu negara dalam menghasilkan barang dan jasa dapat terjadi melalui penambahan faktor-faktor produksi baik dari segi jumlah maupun kualitas. Investasi yang dilakukan juga dapat meningkatkan jumlah modal barang dan perkembangan teknologi. Di samping itu, pertumbuhan penduduk juga dapat memberikan kontribusi melalui peningkatan jumlah tenaga kerja yang disertai dengan peningkatan tingkat pendidikan dan keterampilan.</p>
</section>
<section id="ekspor" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="ekspor"><span class="header-section-number">2.2</span> Ekspor</h3>
<p>Definisi ekspor, menurut Murni yang dikutip dalam Farina dan Husaini (2017), adalah proses pengiriman dan penjualan barang dari suatu negara ke negara lain. Lebih lanjut, ekspor dijelaskan sebagai suatu kegiatan ekonomi yang melibatkan penjualan produk domestik ke pasar internasional. Sukirno, sebagaimana disebutkan oleh Farina dan Husaini (2017), menekankan keuntungan ekspor seperti kemampuan untuk memperluas pasar, meningkatkan devisa negara, dan menciptakan lapangan kerja.</p>
</section>
<section id="impor" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="impor"><span class="header-section-number">2.3</span> Impor</h3>
<p>Impor, seperti dijelaskan oleh Murni dalam Farina dan Husaini (2017), merupakan proses pembelian dan pengenalan barang dari luar negeri ke dalam negeri. Aktivitas impor, yang melibatkan pembelian produk luar negeri untuk kebutuhan konsumsi atau dijual di pasar domestik, tidak selalu dianggap negatif menurut Murni. Sebaliknya, impor juga dapat merangsang aktivitas investasi, terutama jika barang yang diimpor termasuk dalam kategori barang modal, bahan baku, atau barang setengah jadi yang diperlukan dalam sektor industri.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Nilai Ekspor</th>
<th>Nilai Impor</th>
<th>PDB Indonesia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>182.551.754</td>
<td>186.628.631</td>
<td>8.156.497.800.000</td>
</tr>
<tr class="even">
<td>2014</td>
<td>176.036.194</td>
<td>178.179.340</td>
<td>8.564.866.600.000</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>150.282.258</td>
<td>142.694.804</td>
<td>8.982.517.100.000</td>
</tr>
<tr class="even">
<td>2016</td>
<td>144.494.206</td>
<td>135.652.914</td>
<td>9.434.613.400.000</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>168.810.637</td>
<td>156.925.150</td>
<td>9.912.928.100.000</td>
</tr>
<tr class="even">
<td>2018</td>
<td>180.215.036</td>
<td>188.711.246</td>
<td>10.425.851.900.000</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>167.682.996</td>
<td>171.275.737</td>
<td>10.949.155.400.000</td>
</tr>
<tr class="even">
<td>2020</td>
<td>163.306.490</td>
<td>141.622.127</td>
<td>10.722.999.300.000</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>231.587.887</td>
<td>195.694.490</td>
<td>11.120.077.900.000</td>
</tr>
<tr class="even">
<td>2022</td>
<td>291.979.103</td>
<td>237.447.057</td>
<td>11.710.397.800.000</td>
</tr>
</tbody>
</table>
<p>Sumber : Trade Map (https://www.trademap.org/)</p>
<p>Penelitian ini menggunakan data hubungan antara variabel independen dan variabel lainnya, antara nilai ekspor dan impor dengan pertumbuhan ekonomi indonesia</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Penelitian ini menerapkan pendekatan kuantitatif. Sugiyono (2018) menjelaskan bahwa metode penelitian kuantitatif didasarkan pada paradigma positivistik, di mana data penelitian berupa angka-angka yang akan diukur menggunakan statistik sebagai alat uji penghitungan. Pendekatan ini berkaitan dengan masalah yang diteliti untuk menghasilkan kesimpulan. Metode deskriptif digunakan untuk menyajikan gambaran sistematis dan faktual mengenai perkembangan setiap variabel dalam penelitian, termasuk ekspor, impor, dan pertumbuhan ekonomi Indonesia. Paket perangkat lunak yang digunakan dalam penelitian ini meliputi readxl, tidyverse, dan WDI. Selain itu, analisis regresi digunakan untuk menilai pengaruh harga ekspor dan impor terhadap pertumbuhan ekonomi Indonesia selama 10 tahun terakhir .</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> PEMBAHASAN</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Berikut adalah hasil dari plot x dan y, dengan x sebagai kuantitas ekpor kopi Indonesia dan y sebagai nilai (value) ekpor kopi Indonesia. maka didapatkan plot sebagai berikut :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'latihan1.xlsx'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>X, <span class="at">y=</span>Y, <span class="at">s=</span>S))<span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'blue'</span>, <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Tabel 1. Plot Terhadap Pertumbuhan Ekonomi Indonesia"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Nilai Ekspor"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Nilai Impor"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">s=</span><span class="st">"Pertumbuhan Ekonomi"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber: Trade Map"</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"latihan1.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(X<span class="sc">+</span>Y<span class="sc">~</span>S,<span class="at">data=</span>dat)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = X + Y ~ S, data = dat)

Residuals:
      Min        1Q    Median        3Q       Max 
-78224123 -46909630 -17514690  39571427 113621657 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 2.856e+07  1.878e+08   0.152    0.883
S           3.307e-05  1.867e-05   1.771    0.114

Residual standard error: 66290000 on 8 degrees of freedom
Multiple R-squared:  0.2817,    Adjusted R-squared:  0.1919 
F-statistic: 3.137 on 1 and 8 DF,  p-value: 0.1145</code></pre>
</div>
</div>
<p>Hasil estimasi Ordinary Least Squares (OLS) menggunakan model regresi multivariat menunjukkan hubungan antara variabel dependen (tingkat pertumbuhan ekonomi/GDP) dan variabel independen (ekspor dan impor). Dalam konteks ini, jumlah ekspor terlihat memiliki pengaruh positif terhadap pertumbuhan ekonomi, sementara jumlah impor memiliki pengaruh negatif.</p>
<p>Analisis regresi terlihat bahwa nilai F sebesar 31.37 dengan probabilitas 0.1145, menunjukkan adanya pengaruh signifikan secara keseluruhan terhadap pertumbuhan ekonomi Indonesia selama 10 tahun terakhir. Koefisien determinasi (R) sebesar 28.17% menunjukkan sejauh mana variabel independen berkontribusi terhadap variasi dalam pertumbuhan ekonomi, sementara sisanya (71.83%) dipengaruhi oleh faktor-faktor lain yang tidak dimasukkan dalam penelitian.</p>
<p>Selanjutnya, uji parsial dilakukan untuk mengevaluasi apakah variabel independen secara individu signifikan dalam memprediksi nilai variabel dependen. Hasil perhitungan menunjukkan nilai t-hitung sebesar 0.156 dengan probabilitas sebesar 0.88, yang lebih besar dari tingkat signifikansi 0.1. Dengan kata lain, secara parsial, ekspor dan impor tidak berpengaruh secara signifikan terhadap pertumbuhan ekonomi Indonesia selama periode 10 tahun terakhir.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan hasil penelitian, dapat disimpulkan bahwa jumlah ekspor dan jumlah impor memiliki dampak signifikan terhadap pertumbuhan ekonomi. Temuan ini dapat dihubungkan dengan konsep dalam teori perdagangan internasional, di mana peningkatan jumlah ekspor menandakan adanya peningkatan permintaan dari negara lain. Hal ini mendorong peningkatan produksi dalam negeri untuk memenuhi permintaan tersebut, yang pada gilirannya dapat meningkatkan pertumbuhan ekonomi.</p>
<p>Sebaliknya, kenaikan jumlah impor dapat diinterpretasikan sebagai peningkatan barang yang diimpor dari luar negeri. Meskipun dapat memenuhi kebutuhan dalam negeri, hal ini juga berpotensi menurunkan produktivitas industri dalam negeri, yang pada akhirnya dapat menurunkan pertumbuhan ekonomi. Oleh karena itu, untuk mendorong pertumbuhan ekonomi di Indonesia, diperlukan upaya peningkatan produksi dalam negeri.</p>
<p>Secara keseluruhan, hasil penelitian ini memberikan kontribusi untuk memahami hubungan antara perdagangan internasional, produksi dalam negeri, dan pertumbuhan ekonomi, yang penting untuk merancang kebijakan ekonomi yang efektif.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Astuti, I. P., &amp; Ayuningtyas, F. J. (2018). PENGARUH EKSPOR DAN IMPOR TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA. Jurnal Ekonomi &amp; Studi Pembangunan, 19(1), Article 1. https://doi.org/10.18196/jesp.19.1.3836</p>
<p>Badan Pusat Statistik. (n.d.). Retrieved January 12, 2024, from https://www.bps.go.id/exim/</p>
<p>ITC Trade Map. (2022). Retrieved January 12, 2024, from https://www.trademap.org/</p>
<p>Multivariat &amp; Dummy regression. (n.d.). Retrieved January 12, 2024, from https://www.krisna.or.id/metopel/meeting3/index.html#/title-slide</p>
<p>Nasution, D. A. D., Erlina, E., &amp; Muda, I. (2020). Dampak pandemi Covid-19 terhadap perekonomian Indonesia. Jurnal benefita, 5(2), 212-224.</p>
<p>Satu Data Perdagangan. (2022). Retrieved January 12, 2024, from https://satudata.kemendag.go.id/data-informasi/perdagangan-dalam-negeri/produk-domestik-bruto</p>
<p>Wulandari, S., &amp; Lubis, A. S. (2019). Analisis Perkembangan Ekspor Impor Barang Ekonomi di Provinsi Sumatera Utara. Jurnal Administrasi Bisnis, 8(1), 31–36. https://doi.org/10.14710/jab.v8i1.22403</p>
<p>Zulkipli, Z., &amp; Muharir, M. (2021). Dampak Covid-19 Terhadap Perekonomian Indonesia. Jurnal Ilmiah Mahasiswa Ekonomi Syariah (JIMESHA), 1(1), 7-12.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>